#!/bin/sh

if [[ $# -eq 0 ]] || [[ ! -f /Applications/NDN.app/Contents/Platform/"$@" ]] ; then
    echo ERROR: No command or invalid command is specified
    echo
    echo Available commands:
    for command in $(ls /Applications/NDN.app/Contents/Platform/ 2>/dev/null); do
        echo "  $command"
    done
    exit 1
fi

/Applications/NDN.app/Contents/Platform/"$@"
